apiVersion: v1
kind: PersistentVolume
metadata:
  name: Pvlocal
spec:
  capacity:
    storage: 5Gi                     # Size of the Persistent Volume
  accessModes:
    - ReadWriteOnce                   # Access mode: can be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain # Policy for reclaiming the volume after release
  storageClassName: local-storage     # Storage class name for this volume
  hostPath:
   path: "/mnt/data"                # Path on the host where the volume is located